### ISSUE TITLE
Backup restore timeout

### ISSUE THREAD

**Issue by phadaphunk** [stefanzweifel/laravel-backup-restore#54]
My backup is pretty huge and I have get a `Illuminate\Process\Exceptions\ProcessTimedOutException` since the Process used to restore doesn't seem to have a set timeout other than the default one. (after only 60 seconds)

Is it a known limitation or is there a way around that?</div>

**Comment by stefanzweifel** [comment]
@phadaphunk Can you share a bit more about this issue? 

A project at work also has a "huge" (2 GB) backup which I regularly restore on my local machine. That restore process takes ~10-15 minutes and I never ran into this issue.

- How big is this backup? MB? GB? TB?
- Which database type is your target: MySQL? PostgreSQL?
- Are you restoring the database on a server or on your local computer?

We can disable the timeout completely by calling `forever()` in the `DbImporter`-class, but I don't know if this would solve your problem.

You could update your local installation like so.

https://github.com/stefanzweifel/laravel-backup-restore/blob/main/src/Databases/DbImporter.php#L37

```diff
-$process = Process::run($this->getImportCommand($dumpFile, $connection));
+$process = Process::forever()->run($this->getImportCommand($dumpFile, $connection));
```

**Comment by stefanzweifel** [comment]
I've prepared a fix in https://github.com/stefanzweifel/laravel-backup-restore/pull/55, but would like to know, if this would fix your issue, or if the problem lies somewhere else.

Mabye your database of choice itself has a problem importing the dump?

**Comment by phadaphunk** [comment]
@stefanzweifel I will let you know if the forever call fixes my issue.

**Comment by phadaphunk** [comment]
I started a recovery process. In the meantime, here are a few more details : 

- My database is 15GB
- MySQL 8.0
- Restoring in a Docker locally with Laravel Sail

I feel this "should" fix it as there is a default timeout for Processes. In Laravel.  Or maybe the error is hiding another error, I will look into my container to see if I can add logs if it crashes again.

**Comment by stefanzweifel** [comment]
I've merge the PR and a new release has been created.
Thanks again for reporting this.
