### ISSUE TITLE
Mysql password wrong in Win11

### ISSUE THREAD

**Issue by gaglioffo** [stefanzweifel/laravel-backup-restore#78]
Hi @stefanzweifel,
**Scenario:** 
Windows 11, MySql, powershell

**Command:**
php artisan backup:restore --reset --no-interaction

**Resolution for me**
File: _src\Databases\Mysql.php_
Functions: _getMySqlImportCommandForCompressedDump_ and  _getMySqlImportCommandForUncompressedDump_
From: ! empty($password) ? "{$quote}-p'{$password}'{$quote}" : '',
To: ! empty($password) ? "{$quote}-p{$password}{$quote}" : '',
Explanation: Probably the "single quote" before and after the password are converted when run the command

**Error Message in powershell:**
> Importing database dump …
> 
> 
>    Wnx\LaravelBackupRestore\Exceptions\ImportFailed 
> 
>   The import process failed with a none successful exitcode.
> Exitcode
> ========
> 1: 1
> 
> Output
> ======
> &lt;no output&gt;
> 
> Error Output
> ============
> mysql: [Warning] Using a password on the command line interface can be insecure.
> ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
> 
>   at vendor\wnx\laravel-backup-restore\src\Exceptions\ImportFailed.php:16
>      12▕     public static function processDidNotEndSuccessfully(ProcessResult $process): static
>      13▕     {
>      14▕         $processOutput = static::formatProcessOutput($process);
>      15▕
>   ➜  16▕         return new static("The import process failed with a none successful exitcode.{$processOutput}");
>      17▕     }
>      18▕
>      19▕     public static function decompressionFailed(string $filename, string $reason): static
>      20▕     {

**Comment by stefanzweifel** [comment]
Thanks for reporting @gaglioffo! As you can see in #41, we currently can't run the test suite on Windows, so such reports are very valuable.

I've created a hotfix in #79 based on your comments and released that in [v1.4.1](https://github.com/stefanzweifel/laravel-backup-restore/releases/tag/v1.4.1).
