### ISSUE TITLE
Backup taken on windows machine cannot restored on linux and vice versa

### ISSUE THREAD

**Issue by AshrafBasry** [stefanzweifel/laravel-backup-restore#81]
Backup taken on Windows machine cannot be restored on Linux and vice versa because of slash `/` and back slash `\` directory separator in the restoring process
![Screenshot from 2024-10-30 21-04-50](https://github.com/user-attachments/assets/2fb5369a-ad0c-49b4-98e4-83ba31980877)

**Comment by AshrafBasry** [comment]
@stefanzweifel thanks for the quick response
I think i found the issue using this script
```
<?php

$original_file = new ZipArchive();
$original_file->open('only-db-2024-10-27-17-41-30');
$original_file->extractTo('.');
$original_file->close();

$downloaded_file = new ZipArchive();
$downloaded_file->open('2024-10-30-10-18-14-9f1cbc85-71c7-47fe-8d76-bc9546439131.zip');
$downloaded_file->extractTo('.');
$downloaded_file->close();
```
and that's the results
![Screenshot from 2024-10-30 22-32-16](https://github.com/user-attachments/assets/cf5b146a-97df-41a7-9389-53a5f49ab043)


it's the downloaded zip file

**Comment by stefanzweifel** [comment]
@AshrafBasry Thanks for the feedback. 
I guess the `only-db-2024-10-27-17-41-30.zip` does not contain a `db-dumps` folder? Basically you changed how the backup-zip is structured.

If you decompress the original ZIP-file with your Windows OS, everything is okay?

**Comment by AshrafBasry** [comment]
> @AshrafBasry Thanks for the feedback. I guess the `only-db-2024-10-27-17-41-30.zip` does not contain a `db-dumps` folder? Basically you changed how the backup-zip is structured.
> 
> If you decompress the original ZIP-file with your Windows OS, everything is okay?
No i didn't it's the same file

I tested it on both Windows and Linux machines. i used winrar on Windows to unzip and unzip command on linux and it decompressed just fine on both systems and it also decompressed just fine  using php ZipArchive as i mentioned earlier.

this is the error i get :point_down: when i run `php artisan backup:restore --backup=Incubation/only-db-2024-10-27-17-41-30.zip --no-interaction`
![Screenshot from 2024-10-31 00-25-56](https://github.com/user-attachments/assets/9fdfd558-1b68-4df5-abe8-669b4dd2bfae)



the error left this undeleted temp zip file `2024-10-30-10-18-14-9f1cbc85-71c7-47fe-8d76-bc9546439131.zip`  which i used in the earlier test script :point_down: 




> @stefanzweifel thanks for the quick response I think i found the issue using this script
> 
> ```
> <?php
> 
> $original_file = new ZipArchive();
> $original_file->open('only-db-2024-10-27-17-41-30');
> $original_file->extractTo('.');
> $original_file->close();
> 
> $downloaded_file = new ZipArchive();
> $downloaded_file->open('2024-10-30-10-18-14-9f1cbc85-71c7-47fe-8d76-bc9546439131.zip');
> $downloaded_file->extractTo('.');
> $downloaded_file->close();
> ```
> 
> and that's the results ![Screenshot from 2024-10-30 22-32-16](https://private-user-images.githubusercontent.com/20860869/381705130-cf5b146a-97df-41a7-9389-53a5f49ab043.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMjE2MDUsIm5iZiI6MTczMDMyMTMwNSwicGF0aCI6Ii8yMDg2MDg2OS8zODE3MDUxMzAtY2Y1YjE0NmEtOTdkZi00MWE3LTkzODktNTNhNWY0OWFiMDQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDIwNDgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1MjAzNDZjNjEwYmIwNmZhYzVhNDUwMTYwNWI0YzA0NjZmZmEwMmYxOTA3NzZkMGVhOTNkMzA3ZmI1MWYwN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jOVVrCXqe4ueOaOsO7i9ihG84mXIa4nBwSLiWuqQtB0)
> 
> it's the downloaded zip file
> 
> ```
> spin(function () use ($pendingRestore) {
>             Storage::disk($pendingRestore->restoreDisk)
>                 ->writeStream(
>                     $pendingRestore->getPathToLocalCompressedBackup(),
>                     Storage::disk($pendingRestore->disk)->readStream($pendingRestore->backup)
>                 );
>         }, "Downloading {$pendingRestore->backup}");
> ```

**Comment by AshrafBasry** [comment]
It appeared to be my linux dev machine uses outdated php-zip extension (ubuntu-repo) so switching to ondrej/php repo and upgrade to the latest version solves the issue :smile:

**Comment by stefanzweifel** [comment]
@AshrafBasry Great to hear you could resolve this issue. 🙌
